В этом ноутбуке будем собирать информацию по местам привлечения людей по городам, отобранным ранее

In [3]:
import requests
import pandas as pd
import time
import logging

In [4]:
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

In [5]:
logging.basicConfig(
    level=logging.INFO,
    filename="project.log",
    format="%(asctime)s - %(module)s - %(levelname)s - %(funcName)s: %(lineno)d - %(message)s",
    datefmt="%H:%M:%S"
)

logging.info("Логирование настроено")

In [6]:
api_key = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
logging.info('получили апи ключ')
cities = pd.read_excel('cities.xlsx')
logging.info(f'получили список из {len(cities)} городов')
cities.head()

,Unnamed: 0,Город,Регион,Федеральный округ,Население,Наличие аэропорта
0,1,Абакан,Хакасия,Сибирский,184284,True
1,26,Анадырь,Чукотский АО,Дальневосточный,13224,True
2,27,Анапа,Краснодарский край,Южный,84804,True
3,28,Ангарск,Иркутская область,Сибирский,216973,False
4,48,Архангельск,Архангельская область,Северо-Западный,294914,True

Проверим, что выдаст нам поиск по ресторанам в первом попавшемся регионе (потом оказалось, что нам это не понадобится)

https://docs.2gis.com/api/search/categories/reference/2.0/catalog/rubric/search#tag/Kategorii

In [7]:
page_rubric = requests.get(
    'https://catalog.api.2gis.com/2.0/catalog/rubric/search',
    params={
        'key': api_key,
        'q': 'рестораны',
        'region_id': '1',
        'page_size': 5
    }
)

In [10]:
print(page_rubric.status_code)
logging.info(f'тестируем работу с апи 2гиса, статус обращения: {page_rubric.status_code}')
print(page_rubric.json())

200
{'meta': {'api_version': '2.0.20097', 'code': 200, 'issue_date': '20260408'}, 'result': {'items': [{'alias': 'restorany', 'branch_count': 244, 'caption': 'Рестораны', 'id': '164', 'keyword': 'Рестораны', 'name': 'Рестораны', 'org_count': 213, 'parent_id': '2', 'title': 'Рестораны', 'type': 'rubric'}, {'alias': 'bystroe_pitanie', 'branch_count': 1881, 'caption': 'Быстрое питание', 'id': '165', 'keyword': 'Быстрое питание', 'name': 'Быстрое питание', 'org_count': 1208, 'parent_id': '2', 'seo_name': 'Кафе / рестораны быстрого питания (фаст-фуды)', 'title': 'Быстрое питание', 'type': 'rubric'}, {'alias': 'karaoke_zaly', 'branch_count': 59, 'caption': 'Караоке', 'id': '21387', 'keyword': 'Караоке-залы', 'name': 'Караоке-залы', 'org_count': 50, 'parent_id': '2', 'seo_name': 'Караоке-клубы / бары', 'title': 'Караоке', 'type': 'rubric'}], 'total': 3}}

Посмотрим, как смотреть на список регионов

https://docs.2gis.com/api/search/regions/reference/2.0/region/list#tag/Regiony

In [11]:
page_region = requests.get(
    'https://catalog.api.2gis.com/2.0/region/list',
    params={
        'key': api_key,
        'page_size': 5
    }
)

In [12]:
print(page_region.status_code)
logging.info(f'тестируем получение списка регионов, статус обращения: {page_region.status_code}')
print(page_region.json())

200
{'meta': {'api_version': '2.0.20097', 'code': 200, 'issue_date': '20260408'}, 'result': {'items': [{'id': '209', 'name': 'Bakı', 'type': 'region'}, {'id': '173', 'name': 'Cyprus', 'type': 'region'}, {'id': '237', 'name': 'Oman', 'type': 'region'}, {'id': '66', 'name': 'Padova', 'type': 'region'}, {'id': '92', 'name': 'Praha', 'type': 'region'}], 'total': 207}}

Вроде все работает, теперь посмотрим на список всех регионов, которые вообще есть, всего их 207, как мы убедились из предыдущего запроса

In [14]:
page_region_all = requests.get(
    'https://catalog.api.2gis.com/2.0/region/list',
    params={
        'key': api_key,
        'page_size': 207
    }
)

In [15]:
data_regions = page_region_all.json()
regions = data_regions['result']['items']
print(len(regions))
logging.info(f'берем список всех регионов из 2гис, получилось {len(regions)} городов')

207

In [16]:
regions

[{'id': '209', 'name': 'Bakı', 'type': 'region'},
 {'id': '173', 'name': 'Cyprus', 'type': 'region'},
 {'id': '237', 'name': 'Oman', 'type': 'region'},
 {'id': '66', 'name': 'Padova', 'type': 'region'},
 {'id': '92', 'name': 'Praha', 'type': 'region'},
 {'id': '216', 'name': 'Riyadh', 'type': 'region'},
 {'id': '101', 'name': 'Santiago', 'type': 'region'},
 {'id': '99', 'name': 'UAE', 'type': 'region'},
 {'id': '69', 'name': 'Абакан', 'type': 'region'},
 {'id': '248', 'name': 'Абхазия', 'type': 'region'},
 {'id': '196', 'name': 'Актау', 'type': 'region'},
 {'id': '167', 'name': 'Актобе', 'type': 'region'},
 {'id': '67', 'name': 'Алматы', 'type': 'region'},
 {'id': '108', 'name': 'Альметьевск', 'type': 'region'},
 {'id': '155', 'name': 'Анадырь', 'type': 'region'},
 {'id': '106', 'name': 'Армавир', 'type': 'region'},
 {'id': '49', 'name': 'Архангельск', 'type': 'region'},
 {'id': '68', 'name': 'Астана', 'type': 'region'},
 {'id': '8', 'name': 'Астрахань', 'type': 'region'},
 {'id': '168', 'name': 'Атырау', 'type': 'region'},
 {'id': '176', 'name': 'Баган', 'type': 'region'},
 {'id': '121', 'name': 'Балаково', 'type': 'region'},
 {'id': '177', 'name': 'Барабинск', 'type': 'region'},
 {'id': '4', 'name': 'Барнаул', 'type': 'region'},
 {'id': '46', 'name': 'Белгород', 'type': 'region'},
 {'id': '20', 'name': 'Бийск', 'type': 'region'},
 {'id': '52', 'name': 'Благовещенск', 'type': 'region'},
 {'id': '51', 'name': 'Братск', 'type': 'region'},
 {'id': '62', 'name': 'Брянск', 'type': 'region'},
 {'id': '251', 'name': 'Бухара', 'type': 'region'},
 {'id': '77', 'name': 'Великий Новгород', 'type': 'region'},
 {'id': '178', 'name': 'Венгерово', 'type': 'region'},
 {'id': '25', 'name': 'Владивосток', 'type': 'region'},
 {'id': '114', 'name': 'Владикавказ', 'type': 'region'},
 {'id': '59', 'name': 'Владимир', 'type': 'region'},
 {'id': '33', 'name': 'Волгоград', 'type': 'region'},
 {'id': '122', 'name': 'Волгодонск', 'type': 'region'},
 {'id': '78', 'name': 'Вологда', 'type': 'region'},
 {'id': '31', 'name': 'Воронеж', 'type': 'region'},
 {'id': '115', 'name': 'Грозный', 'type': 'region'},
 {'id': '179', 'name': 'Довольное', 'type': 'region'},
 {'id': '277', 'name': 'Дудинка гп', 'type': 'region'},
 {'id': '274', 'name': 'Душанбе', 'type': 'region'},
 {'id': '9', 'name': 'Екатеринбург', 'type': 'region'},
 {'id': '126', 'name': 'Елец', 'type': 'region'},
 {'id': '242', 'name': 'Жезказган', 'type': 'region'},
 {'id': '180', 'name': 'Здвинск', 'type': 'region'},
 {'id': '65', 'name': 'Иваново', 'type': 'region'},
 {'id': '41', 'name': 'Ижевск', 'type': 'region'},
 {'id': '11', 'name': 'Иркутск', 'type': 'region'},
 {'id': '205', 'name': 'Ишим', 'type': 'region'},
 {'id': '70', 'name': 'Йошкар-Ола', 'type': 'region'},
 {'id': '89', 'name': 'КавМинВоды', 'type': 'region'},
 {'id': '21', 'name': 'Казань', 'type': 'region'},
 {'id': '40', 'name': 'Калининград', 'type': 'region'},
 {'id': '61', 'name': 'Калуга', 'type': 'region'},
 {'id': '109', 'name': 'Каменск-Уральский', 'type': 'region'},
 {'id': '127', 'name': 'Камышин', 'type': 'region'},
 {'id': '84', 'name': 'Караганда', 'type': 'region'},
 {'id': '181', 'name': 'Карасук', 'type': 'region'},
 {'id': '278', 'name': 'Караул сп', 'type': 'region'},
 {'id': '182', 'name': 'Каргат', 'type': 'region'},
 {'id': '5', 'name': 'Кемерово', 'type': 'region'},
 {'id': '58', 'name': 'Киров', 'type': 'region'},
 {'id': '129', 'name': 'Ковров', 'type': 'region'},
 {'id': '207', 'name': 'Когалым', 'type': 'region'},
 {'id': '201', 'name': 'Кокшетау', 'type': 'region'},
 {'id': '94', 'name': 'Комсомольск-на-Амуре', 'type': 'region'},
 {'id': '203', 'name': 'Костанай', 'type': 'region'},
 {'id': '34', 'name': 'Кострома', 'type': 'region'},
 {'id': '183', 'name': 'Кочки', 'type': 'region'},
 {'id': '23', 'name': 'Краснодар', 'type': 'region'},
 {'id': '184', 'name': 'Краснозёрское', 'type': 'region'},
 {'id': '7', 'name': 'Красноярск', 'type': 'region'},
 {'id': '174', 'name': 'Крым', 'type': 'region'},
 {'id': '185', 'name': 'Куйбышев', 'type': 'region'},
 {'id': '210', 'name': 'Кумертау', 'type': 'region'},
 {'id': '186', 'name': 'Купино', 'type': 'region'},
 {'id': '10', 'name': 'Курган', 'type': 'region'},
 {'id': '73', 'name': 'Курск', 'type': 'region'},
 {'id': '240', 'name': 'Кызылорда', 'type': 'region'},
 {'id': '112', 'name': 'Кыргызстан', 'type': 'region'},
 {'id': '187', 'name': 'Кыштовка', 'type': 'region'},
 {'id': '86', 'name': 'Ленинск-Кузнецкий', 'type': 'region'},
 {'id': '56', 'name': 'Липецк', 'type': 'region'},
 {'id': '158', 'name': 'Магадан', 'type': 'region'},
 {'id': '26', 'name': 'Магнитогорск', 'type': 'region'},
 {'id': '131', 'name': 'Майкоп', 'type': 'region'},
 {'id': '113', 'name': 'Махачкала', 'type': 'region'},
 {'id': '87', 'name': 'Миасс и Златоуст', 'type': 'region'},
 {'id': '217', 'name': 'Минск', 'type': 'region'},
 {'id': '245', 'name': 'Мичуринск', 'type': 'region'},
 {'id': '32', 'name': 'Москва', 'type': 'region'},
 {'id': '241', 'name': 'Московская область', 'type': 'region'},
 {'id': '96', 'name': 'Мурманская область', 'type': 'region'},
 {'id': '132', 'name': 'Муром', 'type': 'region'},
 {'id': '29', 'name': 'Набережные Челны', 'type': 'region'},
 {'id': '154', 'name': 'Назрань', 'type': 'region'},
 {'id': '134', 'name': 'Нальчик', 'type': 'region'},
 {'id': '159', 'name': 'Нарьян-Мар', 'type': 'region'},
 {'id': '82', 'name': 'Находка', 'type': 'region'},
 {'id': '135', 'name': 'Невинномысск', 'type': 'region'},
 {'id': '12', 'name': 'Нижневартовск', 'type': 'region'},
 {'id': '19', 'name': 'Нижний Новгород', 'type': 'region'},
 {'id': '45', 'name': 'Нижний Тагил', 'type': 'region'},
 {'id': '6', 'name': 'Новокузнецк', 'type': 'region'},
 {'id': '74', 'name': 'Новороссийск', 'type': 'region'},
 {'id': '1', 'name': 'Новосибирск', 'type': 'region'},
 {'id': '137', 'name': 'Новочеркасск', 'type': 'region'},
 {'id': '138', 'name': 'Новошахтинск', 'type': 'region'},
 {'id': '139', 'name': 'Новый Уренгой', 'type': 'region'},
 {'id': '76', 'name': 'Норильск', 'type': 'region'},
 {'id': '103', 'name': 'Ноябрьск', 'type': 'region'},
 {'id': '202', 'name': 'Нягань', 'type': 'region'},
 {'id': '2', 'name': 'Омск', 'type': 'region'},
 {'id': '48', 'name': 'Оренбург', 'type': 'region'},
 {'id': '142', 'name': 'Орск', 'type': 'region'},
 {'id': '71', 'name': 'Орёл', 'type': 'region'},
 {'id': '111', 'name': 'Павлодар', 'type': 'region'},
 {'id': '42', 'name': 'Пенза', 'type': 'region'},
 {'id': '16', 'name': 'Пермь', 'type': 'region'},
 {'id': '80', 'name': 'Петрозаводск', 'type': 'region'},
 {'id': '170', 'name': 'Петропавловск', 'type': 'region'},
 {'id': '95', 'name': 'Петропавловск-Камчатский', 'type': 'region'},
 {'id': '213', 'name': 'Пикалево', 'type': 'region'},
 {'id': '90', 'name': 'Псков', 'type': 'region'},
 {'id': '27', 'name': 'Республика Алтай', 'type': 'region'},
 {'id': '24', 'name': 'Ростов-на-Дону', 'type': 'region'},
 {'id': '143', 'name': 'Рубцовск', 'type': 'region'},
 {'id': '144', 'name': 'Рыбинск', 'type': 'region'},
 {'id': '44', 'name': 'Рязань', 'type': 'region'},
 {'id': '160', 'name': 'Салехард', 'type': 'region'},
 {'id': '18', 'name': 'Самара', 'type': 'region'},
 {'id': '247', 'name': 'Самарканд', 'type': 'region'},
 {'id': '38', 'name': 'Санкт-Петербург', 'type': 'region'},
 {'id': '85', 'name': 'Саранск', 'type': 'region'},
 {'id': '43', 'name': 'Саратов', 'type': 'region'},
 {'id': '188', 'name': 'Северное', 'type': 'region'},
 {'id': '169', 'name': 'Семей', 'type': 'region'},
 {'id': '215', 'name': 'Сланцы', 'type': 'region'},
 {'id': '63', 'name': 'Смоленск', 'type': 'region'},
 {'id': '30', 'name': 'Сочи', 'type': 'region'},
 {'id': '57', 'name': 'Ставрополь', 'type': 'region'},
 {'id': '60', 'name': 'Старый Оскол', 'type': 'region'},
 {'id': '54', 'name': 'Стерлитамак', 'type': 'region'},
 {'id': '39', 'name': 'Сургут', 'type': 'region'},
 {'id': '72', 'name': 'Сыктывкар', 'type': 'region'},
 {'id': '214', 'name': 'Сясьстрой', 'type': 'region'},
 {'id': '116', 'name': 'Таганрог', 'type': 'region'},
 {'id': '81', 'name': 'Тамбов', 'type': 'region'},
 {'id': '221', 'name': 'Тараз', 'type': 'region'},
 {'id': '189', 'name': 'Татарск', 'type': 'region'},
 {'id': '208', 'name': 'Ташкент', 'type': 'region'},
 {'id': '47', 'name': 'Тверь', 'type': 'region'},
 {'id': '97', 'name': 'Тобольск', 'type': 'region'},
 {'id': '22', 'name': 'Тольятти', 'type': 'region'},
 {'id': '3', 'name': 'Томск', 'type': 'region'},
 {'id': '36', 'name': 'Тула', 'type': 'region'},
 {'id': '232', 'name': 'Туркестан', 'type': 'region'},
 {'id': '13', 'name': 'Тюмень', 'type': 'region'},
 {'id': '190', 'name': 'Убинское', 'type': 'region'},
 {'id': '37', 'name': 'Улан-Удэ', 'type': 'region'},
 {'id': '55', 'name': 'Ульяновск', 'type': 'region'},
 {'id': '162', 'name': 'Уральск', 'type': 'region'},
 {'id': '83', 'name': 'Уссурийск', 'type': 'region'},
 {'id': '91', 'name': 'Усть-Каменогорск', 'type': 'region'},
 {'id': '191', 'name': 'Усть-Тарка', 'type': 'region'},
 {'id': '17', 'name': 'Уфа', 'type': 'region'},
 {'id': '204', 'name': 'Ухта', 'type': 'region'},
 {'id': '35', 'name': 'Хабаровск', 'type': 'region'},
 {'id': '150', 'name': 'Ханты-Мансийск', 'type': 'region'},
 {'id': '151', 'name': 'Хасавюрт', 'type': 'region'},
 {'id': '276', 'name': 'Хатанга сп', 'type': 'region'},
 {'id': '192', 'name': 'Чаны', 'type': 'region'},
 {'id': '53', 'name': 'Чебоксары', 'type': 'region'},
 {'id': '15', 'name': 'Челябинск', 'type': 'region'},
 {'id': '118', 'name': 'Черкесск', 'type': 'region'},
 {'id': '193', 'name': 'Чистоозёрное', 'type': 'region'},
 {'id': '64', 'name': 'Чита', 'type': 'region'},
 {'id': '166', 'name': 'Чулым', 'type': 'region'},
 {'id': '152', 'name': 'Шахты', 'type': 'region'},
 {'id': '206', 'name': 'Шерегеш', 'type': 'region'},
 {'id': '161', 'name': 'Шымкент', 'type': 'region'},
 {'id': '252', 'name': 'Экибастуз', 'type': 'region'},
 {'id': '153', 'name': 'Элиста', 'type': 'region'},
 {'id': '88', 'name': 'Южно-Сахалинск', 'type': 'region'},
 {'id': '50', 'name': 'Якутск', 'type': 'region'},
 {'id': '28', 'name': 'Ярославль', 'type': 'region'},
 {'id': '253', 'name': 'Հայաստան', 'type': 'region'},
 {'id': '229', 'name': 'الباحة', 'type': 'region'},
 {'id': '233', 'name': 'البحرين', 'type': 'region'},
 {'id': '230', 'name': 'الجوف', 'type': 'region'},
 {'id': '226', 'name': 'الحدود الشمالية', 'type': 'region'},
 {'id': '220', 'name': 'الدمام', 'type': 'region'},
 {'id': '222', 'name': 'القاسم', 'type': 'region'},
 {'id': '235', 'name': 'الكويت', 'type': 'region'},
 {'id': '219', 'name': 'المدينة', 'type': 'region'},
 {'id': '243', 'name': 'بصرة', 'type': 'region'},
 {'id': '224', 'name': 'تبوك', 'type': 'region'},
 {'id': '227', 'name': 'جازان', 'type': 'region'},
 {'id': '225', 'name': 'حائل', 'type': 'region'},
 {'id': '234', 'name': 'دولة قطر', 'type': 'region'},
 {'id': '223', 'name': 'عسير', 'type': 'region'},
 {'id': '218', 'name': 'مكة', 'type': 'region'},
 {'id': '228', 'name': 'نجران', 'type': 'region'},
 {'id': '250', 'name': 'نيوم', 'type': 'region'},
 {'id': '255', 'name': 'ბათუმი', 'type': 'region'}]

Убедились, что их 207 и посмотрели на структуру выдачи, теперь посмотрим на них в более удобном формате

In [17]:
for region in regions:
    print(region['id'], region['name'])

209 Bakı
173 Cyprus
237 Oman
66 Padova
92 Praha
216 Riyadh
101 Santiago
99 UAE
69 Абакан
248 Абхазия
196 Актау
167 Актобе
67 Алматы
108 Альметьевск
155 Анадырь
106 Армавир
49 Архангельск
68 Астана
8 Астрахань
168 Атырау
176 Баган
121 Балаково
177 Барабинск
4 Барнаул
46 Белгород
20 Бийск
52 Благовещенск
51 Братск
62 Брянск
251 Бухара
77 Великий Новгород
178 Венгерово
25 Владивосток
114 Владикавказ
59 Владимир
33 Волгоград
122 Волгодонск
78 Вологда
31 Воронеж
115 Грозный
179 Довольное
277 Дудинка гп
274 Душанбе
9 Екатеринбург
126 Елец
242 Жезказган
180 Здвинск
65 Иваново
41 Ижевск
11 Иркутск
205 Ишим
70 Йошкар-Ола
89 КавМинВоды
21 Казань
40 Калининград
61 Калуга
109 Каменск-Уральский
127 Камышин
84 Караганда
181 Карасук
278 Караул сп
182 Каргат
5 Кемерово
58 Киров
129 Ковров
207 Когалым
201 Кокшетау
94 Комсомольск-на-Амуре
203 Костанай
34 Кострома
183 Кочки
23 Краснодар
184 Краснозёрское
7 Красноярск
174 Крым
185 Куйбышев
210 Кумертау
186 Купино
10 Курган
73 Курск
240 Кызылорда
112 Кыргызстан
187 Кыштовка
86 Ленинск-Кузнецкий
56 Липецк
158 Магадан
26 Магнитогорск
131 Майкоп
113 Махачкала
87 Миасс и Златоуст
217 Минск
245 Мичуринск
32 Москва
241 Московская область
96 Мурманская область
132 Муром
29 Набережные Челны
154 Назрань
134 Нальчик
159 Нарьян-Мар
82 Находка
135 Невинномысск
12 Нижневартовск
19 Нижний Новгород
45 Нижний Тагил
6 Новокузнецк
74 Новороссийск
1 Новосибирск
137 Новочеркасск
138 Новошахтинск
139 Новый Уренгой
76 Норильск
103 Ноябрьск
202 Нягань
2 Омск
48 Оренбург
142 Орск
71 Орёл
111 Павлодар
42 Пенза
16 Пермь
80 Петрозаводск
170 Петропавловск
95 Петропавловск-Камчатский
213 Пикалево
90 Псков
27 Республика Алтай
24 Ростов-на-Дону
143 Рубцовск
144 Рыбинск
44 Рязань
160 Салехард
18 Самара
247 Самарканд
38 Санкт-Петербург
85 Саранск
43 Саратов
188 Северное
169 Семей
215 Сланцы
63 Смоленск
30 Сочи
57 Ставрополь
60 Старый Оскол
54 Стерлитамак
39 Сургут
72 Сыктывкар
214 Сясьстрой
116 Таганрог
81 Тамбов
221 Тараз
189 Татарск
208 Ташкент
47 Тверь
97 Тобольск
22 Тольятти
3 Томск
36 Тула
232 Туркестан
13 Тюмень
190 Убинское
37 Улан-Удэ
55 Ульяновск
162 Уральск
83 Уссурийск
91 Усть-Каменогорск
191 Усть-Тарка
17 Уфа
204 Ухта
35 Хабаровск
150 Ханты-Мансийск
151 Хасавюрт
276 Хатанга сп
192 Чаны
53 Чебоксары
15 Челябинск
118 Черкесск
193 Чистоозёрное
64 Чита
166 Чулым
152 Шахты
206 Шерегеш
161 Шымкент
252 Экибастуз
153 Элиста
88 Южно-Сахалинск
50 Якутск
28 Ярославль
253 Հայաստան
229 الباحة
233 البحرين
230 الجوف
226 الحدود الشمالية
220 الدمام
222 القاسم
235 الكويت
219 المدينة
243 بصرة
224 تبوك
227 جازان
225 حائل
234 دولة قطر
223 عسير
218 مكة
228 نجران
250 نيوم
255 ბათუმი

Теперь проверим, сколько из этих регионов совпадают с нашими городами

In [18]:
regions_dict = {}
for region in regions:
    regions_dict[region['name']] = region['id']

regions_dict

{'Bakı': '209',
 'Cyprus': '173',
 'Oman': '237',
 'Padova': '66',
 'Praha': '92',
 'Riyadh': '216',
 'Santiago': '101',
 'UAE': '99',
 'Абакан': '69',
 'Абхазия': '248',
 'Актау': '196',
 'Актобе': '167',
 'Алматы': '67',
 'Альметьевск': '108',
 'Анадырь': '155',
 'Армавир': '106',
 'Архангельск': '49',
 'Астана': '68',
 'Астрахань': '8',
 'Атырау': '168',
 'Баган': '176',
 'Балаково': '121',
 'Барабинск': '177',
 'Барнаул': '4',
 'Белгород': '46',
 'Бийск': '20',
 'Благовещенск': '52',
 'Братск': '51',
 'Брянск': '62',
 'Бухара': '251',
 'Великий Новгород': '77',
 'Венгерово': '178',
 'Владивосток': '25',
 'Владикавказ': '114',
 'Владимир': '59',
 'Волгоград': '33',
 'Волгодонск': '122',
 'Вологда': '78',
 'Воронеж': '31',
 'Грозный': '115',
 'Довольное': '179',
 'Дудинка гп': '277',
 'Душанбе': '274',
 'Екатеринбург': '9',
 'Елец': '126',
 'Жезказган': '242',
 'Здвинск': '180',
 'Иваново': '65',
 'Ижевск': '41',
 'Иркутск': '11',
 'Ишим': '205',
 'Йошкар-Ола': '70',
 'КавМинВоды': '89',
 'Казань': '21',
 'Калининград': '40',
 'Калуга': '61',
 'Каменск-Уральский': '109',
 'Камышин': '127',
 'Караганда': '84',
 'Карасук': '181',
 'Караул сп': '278',
 'Каргат': '182',
 'Кемерово': '5',
 'Киров': '58',
 'Ковров': '129',
 'Когалым': '207',
 'Кокшетау': '201',
 'Комсомольск-на-Амуре': '94',
 'Костанай': '203',
 'Кострома': '34',
 'Кочки': '183',
 'Краснодар': '23',
 'Краснозёрское': '184',
 'Красноярск': '7',
 'Крым': '174',
 'Куйбышев': '185',
 'Кумертау': '210',
 'Купино': '186',
 'Курган': '10',
 'Курск': '73',
 'Кызылорда': '240',
 'Кыргызстан': '112',
 'Кыштовка': '187',
 'Ленинск-Кузнецкий': '86',
 'Липецк': '56',
 'Магадан': '158',
 'Магнитогорск': '26',
 'Майкоп': '131',
 'Махачкала': '113',
 'Миасс и Златоуст': '87',
 'Минск': '217',
 'Мичуринск': '245',
 'Москва': '32',
 'Московская область': '241',
 'Мурманская область': '96',
 'Муром': '132',
 'Набережные Челны': '29',
 'Назрань': '154',
 'Нальчик': '134',
 'Нарьян-Мар': '159',
 'Находка': '82',
 'Невинномысск': '135',
 'Нижневартовск': '12',
 'Нижний Новгород': '19',
 'Нижний Тагил': '45',
 'Новокузнецк': '6',
 'Новороссийск': '74',
 'Новосибирск': '1',
 'Новочеркасск': '137',
 'Новошахтинск': '138',
 'Новый Уренгой': '139',
 'Норильск': '76',
 'Ноябрьск': '103',
 'Нягань': '202',
 'Омск': '2',
 'Оренбург': '48',
 'Орск': '142',
 'Орёл': '71',
 'Павлодар': '111',
 'Пенза': '42',
 'Пермь': '16',
 'Петрозаводск': '80',
 'Петропавловск': '170',
 'Петропавловск-Камчатский': '95',
 'Пикалево': '213',
 'Псков': '90',
 'Республика Алтай': '27',
 'Ростов-на-Дону': '24',
 'Рубцовск': '143',
 'Рыбинск': '144',
 'Рязань': '44',
 'Салехард': '160',
 'Самара': '18',
 'Самарканд': '247',
 'Санкт-Петербург': '38',
 'Саранск': '85',
 'Саратов': '43',
 'Северное': '188',
 'Семей': '169',
 'Сланцы': '215',
 'Смоленск': '63',
 'Сочи': '30',
 'Ставрополь': '57',
 'Старый Оскол': '60',
 'Стерлитамак': '54',
 'Сургут': '39',
 'Сыктывкар': '72',
 'Сясьстрой': '214',
 'Таганрог': '116',
 'Тамбов': '81',
 'Тараз': '221',
 'Татарск': '189',
 'Ташкент': '208',
 'Тверь': '47',
 'Тобольск': '97',
 'Тольятти': '22',
 'Томск': '3',
 'Тула': '36',
 'Туркестан': '232',
 'Тюмень': '13',
 'Убинское': '190',
 'Улан-Удэ': '37',
 'Ульяновск': '55',
 'Уральск': '162',
 'Уссурийск': '83',
 'Усть-Каменогорск': '91',
 'Усть-Тарка': '191',
 'Уфа': '17',
 'Ухта': '204',
 'Хабаровск': '35',
 'Ханты-Мансийск': '150',
 'Хасавюрт': '151',
 'Хатанга сп': '276',
 'Чаны': '192',
 'Чебоксары': '53',
 'Челябинск': '15',
 'Черкесск': '118',
 'Чистоозёрное': '193',
 'Чита': '64',
 'Чулым': '166',
 'Шахты': '152',
 'Шерегеш': '206',
 'Шымкент': '161',
 'Экибастуз': '252',
 'Элиста': '153',
 'Южно-Сахалинск': '88',
 'Якутск': '50',
 'Ярославль': '28',
 'Հայաստան': '253',
 'الباحة': '229',
 'البحرين': '233',
 'الجوف': '230',
 'الحدود الشمالية': '226',
 'الدمام': '220',
 'القاسم': '222',
 'الكويت': '235',
 'المدينة': '219',
 'بصرة': '243',
 'تبوك': '224',
 'جازان': '227',
 'حائل': '225',
 'دولة قطر': '234',
 'عسير': '223',
 'مكة': '218',
 'نجران': '228',
 'نيوم': '250',
 'ბათუმი': '255'}

In [19]:
found = {}
not_found = []

for city in cities['Город']:
    if city in regions_dict:
        found[city] = regions_dict[city]
    else:
        not_found.append(city)

print(len(found))
print(len(not_found))

79
25

То есть, есть 25 городов, которых не нашлось в 2ГИС, посмотрим, что это за города

In [20]:
not_found

['Анапа',
 'Ангарск',
 'Балашиха',
 'Великие Луки',
 'Волжский',
 'Горно-Алтайск',
 'Дзержинск',
 'Жуковский',
 'Златоуст',
 'Королёв',
 'Красногорск',
 'Люберцы',
 'Магас',
 'Миасс',
 'Минеральные Воды',
 'Мурманск',
 'Мытищи',
 'Нижнекамск',
 'Одинцово',
 'Подольск',
 'Северодвинск',
 'Симферополь',
 'Химки',
 'Череповец',
 'Энгельс']

Я посмотрел в наши списки, к сожалению, большинства городов реально у нас нет, но, есть 3 интересные вещи:

1) Миасс и Златоуст есть в обоих наших списках, но в 2ГИСе они собраны в 1 единый регион, буквально: "Миасс и Златоуст", поэтому их добавим вручную

2) В 2ГИСе нет Мурманска, но есть Мурманская область, но Мурманск является крупнейшим городом своей области, поэтому тоже добавим

3) В 2ГИСе нет многих городов мос области, которые есть в нашем списке городов, но есть единая "Московская область". Однако, так как там все же много городов, добавлять мы ее не будем

In [21]:
found['Златоуст'] = '87'
found['Миасс'] = '87'
found['Мурманск'] = '96'

print(len(found))
print(len(not_found) - 3)
print((len(found) / cities.shape[0]) * 100)
logging.info(f'посмотрели частичные и полные совпадения по городам из нашего файла и из 2гиса, покрываем {(len(found) / cities.shape[0]) * 100}% наших городов')

82
22
78.84615384615384

Почти 79% наших городов будут в 2ГИС

Теперь посмотрим, какие конкретно рубрики нам нужны, проверим, какие категории рубрик вообще существуют

https://docs.2gis.com/api/search/categories/reference/2.0/catalog/rubric/list#tag/Kategorii

In [23]:
rubric_categories_response = requests.get(
    'https://catalog.api.2gis.com/2.0/catalog/rubric/list',
    params={
        'key': api_key,
        'region_id': '1',
        'page_size': 50
    }
)

rubric_cat_data = rubric_categories_response.json()
rubric_cat_items = rubric_cat_data['result']['items']

print(rubric_cat_data['result']['total']) # меньше 50, значит все вывели
for item in rubric_cat_items:
    print(f'id: {item['id']}, название: {item['name']}')
logging.info('смотрим, какие конкретно виды мест притяжения людей нас заинтересуют')

28
id: 5419, название: Аварийные / справочные / экстренные службы
id: 42903, название: Автосервис / Автотовары
id: 1, название: Город / Власть
id: 2, название: Досуг / Развлечения / Общественное питание
id: 19532, название: Интернет / Связь / Информационные технологии
id: 10, название: Коммунальные / бытовые / ритуальные услуги
id: 3, название: Компьютеры / Бытовая техника / Офисная техника
id: 4, название: Культура / Искусство / Религия
id: 787, название: Мебель / Материалы / Фурнитура
id: 5, название: Медицина / Здоровье / Красота
id: 112663, название: Места
id: 13, название: Металлы / Топливо / Химия
id: 15, название: Оборудование / Инструмент
id: 6, название: Образование / Работа / Карьера
id: 1035, название: Одежда / Обувь
id: 1621, название: Охрана / Безопасность
id: 14, название: Продукты питания / Напитки
id: 7, название: Реклама / Полиграфия / СМИ
id: 8, название: Спорт / Отдых / Туризм
id: 42867, название: Строительные / отделочные материалы
id: 9, название: Строительство / Недвижимость / Ремонт
id: 42872, название: Текстиль / Предметы интерьера
id: 746, название: Товары для животных / Ветеринария
id: 6547, название: Торговые комплексы / Спецмагазины
id: 12, название: Транспорт / Грузоперевозки
id: 11, название: Хозтовары / Канцелярия / Упаковка
id: 42863, название: Электроника / Электротехника
id: 969, название: Юридические / финансовые / бизнес-услуги

Меня здесь привлекло 4 категории: 2 (Досуг / Развлечения / Общественное питание), 4 (Культура / Искусство / Религия), 112663 (Места) и 8 (Спорт / Отдых / Туризм)

Кажется, именно в этих категориях будет то, что влияет на привлекательность города для туриста

Посмотрим глубже в каждую из категорий, начнем со второй

In [24]:
rubric_sub_response = requests.get(
    'https://catalog.api.2gis.com/2.0/catalog/rubric/list',
    params={
        'key': api_key,
        'region_id': '1',
        'parent_id': '2',
        'page_size': 50
    }
)

rubric_sub_data = rubric_sub_response.json()
rubric_sub_items = rubric_sub_data['result']['items']

for item in rubric_sub_items:
    print(f'id: {item['id']}, название: {item['name']}')

id: 112455, название: Авиатренажёры
id: 113336, название: Автоматы фотопечати
id: 537, название: Аквапарки
id: 72370, название: Антикафе
id: 110305, название: Аренда беседок
id: 112792, название: Аренда детских лофтов
id: 110373, название: Аренда мебели для мероприятий
id: 110308, название: Аренда шатров и конструкций
id: 110358, название: Аттракционы
id: 100772, название: Аэродинамические комплексы
id: 110384, название: Аэросъёмка
id: 946, название: Бани и сауны
id: 10803, название: Банкетные залы
id: 159, название: Бары
id: 21497, название: Билеты на мероприятия
id: 169, название: Бильярдные залы
id: 24169, название: Ботанический сад
id: 170, название: Боулинг
id: 171, название: Букмекеры
id: 165, название: Быстрое питание
id: 110304, название: Верёвочные парки
id: 24099, название: Выставка насекомых
id: 8151, название: Дайвинг-клубы
id: 9508, название: Дельфинарий
id: 16743, название: Детские игровые залы
id: 113330, название: Детские развлекательные автоматы
id: 13787, название: Дома культуры
id: 1203, название: Доставка еды
id: 113573, название: Зоокафе
id: 167, название: Зоопарк
id: 112609, название: Караоке-боксы
id: 21387, название: Караоке-залы
id: 161, название: Кафе
id: 112658, название: Кафе-кондитерские
id: 110300, название: Квесты
id: 112464, название: Квизы
id: 9786, название: Кейтеринг
id: 102044, название: Киноаттракционы
id: 192, название: Кинотеатры
id: 110430, название: Клубы видеоигр
id: 112550, название: Клубы настольных игр
id: 67763, название: Комбинаты питания
id: 51001, название: Концертные залы
id: 162, название: Кофейни
id: 112719, название: Кофейные автоматы
id: 16677, название: Кулинарии
id: 14967, название: Культурно-досуговые центры
id: 112394, название: Курсы робототехники
id: 13789, название: Курсы творчества для детей
id: 112619, название: Лектории

Отсюда мы возьмем рестораны (164)

Посморим остальные категории

In [25]:
for cat in ['4', '112663', '8']:
    rubric_sub_response = requests.get(
        'https://catalog.api.2gis.com/2.0/catalog/rubric/list',
        params={
            'key': api_key,
            'region_id': '1',
            'parent_id': cat,
            'page_size': 100
        }
    )
    rubric_sub_items = rubric_sub_response.json()['result']['items']
    print(f'------ {cat} ------')
    for item in rubric_sub_items:
        print(f'id: {item['id']}, название: {item['name']}')

    time.sleep(0.5)

------ 4 ------
id: 686, название: Антиквариат
id: 112395, название: Багетные мастерские
id: 189, название: Библиотеки
id: 18574, название: Воскресные школы
id: 112657, название: Гончарные мастерские
id: 112875, название: Городские мероприятия
id: 10887, название: Городские оркестры
id: 54914, название: Дацаны
id: 51206, название: Духовные учебные заведения
id: 51323, название: Иконописные мастерские
id: 113326, название: Интерактивные музеи
id: 191, название: Киностудии
id: 13374, название: Мечети
id: 19575, название: Монастыри
id: 193, название: Музеи
id: 110420, название: Нумизматика
id: 52186, название: Паломнические поездки
id: 11647, название: Планетарий
id: 110361, название: Подвесы и освещение картин
id: 19576, название: Приходы
id: 1175, название: Религиозные организации
id: 12249, название: Религиозные товары
id: 51379, название: Реставрация исторических памятников
id: 54063, название: Синагога
id: 199, название: Театры
id: 200, название: Филармония
id: 113154, название: Филателия
id: 51207, название: Хоровые капеллы
id: 194, название: Храмы / Соборы / Церкви
id: 190, название: Художественные выставки
id: 516, название: Художественные мастерские
id: 515, название: Художественные товары
id: 19577, название: Часовни
------ 112663 ------
id: 113468, название: Авиапамятники
id: 112929, название: Беседки
id: 112921, название: Вертолётные площадки
id: 113289, название: Вершины гор
id: 112906, название: Водопады
id: 112868, название: Водопроводные колонки / колодцы
id: 112924, название: Вольеры с животными / птицами
id: 112910, название: Дайв-споты
id: 112884, название: Детские площадки
id: 113612, название: Дог-боксы
id: 112917, название: Душ на пляже
id: 112919, название: Ж/д переезды
id: 112670, название: Интересные здания
id: 112862, название: Информационные точки
id: 113118, название: Ледяные горки
id: 112823, название: Мангальные зоны
id: 113800, название: Мемы на карте
id: 112908, название: Места для выгула собак
id: 112922, название: Места для курения
id: 112931, название: Места захоронения
id: 112918, название: Мост
id: 112870, название: Новогодние ёлки
id: 112900, название: Памятники и скульптуры
id: 112901, название: Памятные доски
id: 113470, название: Пещеры
id: 112899, название: Площадки Work Out
id: 112913, название: Площадки для пейнтбола
id: 112927, название: Придорожные зоны отдыха
id: 112668, название: Природные достопримечательности
id: 112916, название: Раздевалки на пляже
id: 113291, название: Религиозные объекты
id: 112926, название: Родники
id: 112907, название: Руины
id: 112912, название: Сады / цветники
id: 113471, название: Скалы
id: 112925, название: Спортивные площадки
id: 112905, название: Стрит-арт
id: 112915, название: Сцены
id: 113467, название: Теннисные столы
id: 112928, название: Тиры
id: 113292, название: Точки интереса
id: 112872, название: Уличные катки
id: 113465, название: Уличные тренажёры
id: 112911, название: Усадьбы
id: 112720, название: Фонтаны
id: 112932, название: Эстакады
------ 8 ------
id: 51646, название: Авиаклубы
id: 112548, название: Авто- и мотодромы
id: 110332, название: Аквааэробика
id: 111005, название: Аренда коттеджей / гостевых домов
id: 110498, название: Аренда спортивных площадок
id: 112685, название: Атрибутика для болельщиков
id: 547, название: Базы отдыха
id: 261, название: Бассейны
id: 110427, название: Батутные центры
id: 110387, название: Бронирование гостиниц
id: 71232, название: Велнес-залы
id: 809, название: Велосипеды
id: 631, название: Водно-спортивная техника
id: 113083, название: Водные прогулки
id: 68951, название: Военно-патриотические клубы
id: 110377, название: ВУМ гимнастика
id: 111582, название: Герои с нашего двора
id: 51221, название: Гольф-клубы
id: 24472, название: Горнолыжные комплексы
id: 111540, название: Горнолыжные подъёмники
id: 269, название: Гостиницы
id: 270, название: Детские лагеря
id: 774, название: Детское игровое оборудование
id: 112677, название: Дневные детские лагеря
id: 113723, название: Запчасти для велосипедов
id: 113646, название: Канатные дороги
id: 51008, название: Картинг
id: 11974, название: Каток
id: 19487, название: Квартиры посуточно
id: 70348, название: Кемпинги
id: 112684, название: Клубы настольного тенниса
id: 262, название: Конные клубы
id: 19601, название: Круизы
id: 113042, название: Ледовые дворцы
id: 110490, название: Лодочные станции
id: 112877, название: Лыжные базы
id: 47105, название: Наградная продукция
id: 111539, название: Обучение горнолыжному спорту
id: 4515, название: Обучение танцам
id: 112545, название: Общежития для рабочих
id: 25108, название: Организация активных туров
id: 113082, название: Организация выездного детского лагеря
id: 112541, название: Отели для свиданий
id: 110491, название: Охотничьи центры
id: 113419, название: Падел-корты
id: 113726, название: Плавание для грудничков
id: 51414, название: Подводное снаряжение
id: 20863, название: Помощь в оформлении загранпаспортов
id: 266, название: Профессиональные спортивные клубы
id: 52495, название: Ремонт спортивного инвентаря
id: 110423, название: Ремонт спортивного оборудования
id: 112855, название: Ремонт спортивной экипировки
id: 110422, название: Ремонт товаров для охоты
id: 51244, название: Рыболовные центры
id: 110303, название: Скалодромы
id: 99736, название: Сквош-корты
id: 607, название: Спортивная одежда и обувь
id: 696, название: Спортивное оборудование
id: 1233, название: Спортивное питание
id: 51370, название: Спортивно-интеллектуальные клубы
id: 61066, название: Спортивно-развлекательные товары
id: 264, название: Спортивно-технические клубы
id: 113725, название: Спортивные арены
id: 51256, название: Спортивные секции
id: 633, название: Спортивные школы
id: 764, название: Спортивный инвентарь
id: 309, название: Спортивный прокат
id: 634, название: Стадионы / Спортивные арены
id: 51241, название: Теннисные корты
id: 53139, название: Товары для конного спорта
id: 384, название: Товары для охоты
id: 259, название: Товары для рыбалки
id: 505, название: Товары для туризма и отдыха
id: 267, название: Тренажёрные залы
id: 272, название: Турагентства
id: 23494, название: Турагентства внутреннего туризма
id: 16615, название: Туроператоры
id: 112878, название: Тюбинговые трассы
id: 20773, название: Федерации спорта
id: 268, название: Фитнес-клубы
id: 52681, название: Хостелы
id: 112588, название: Центры адаптивного спорта
id: 20228, название: Центры йоги
id: 112621, название: Центры тестирования ГТО
id: 9965, название: Яхт-клубы

Из этих категорий возьмем следующее: музеи (193), театры (199), природные достопримечательности (112668) и интересные здания (112670)

Итого, список такой:

In [26]:
rubrics = {
    'Рестораны': '164',
    'Музеи': '193',
    'Театры': '199',
    'Природные достопримечательности': '112668',
    'Интересные здания': '112670'
}
logging.info(f'выбрали конкретные виды мест (рубрики), это {[rub for rub in rubrics]}')

Сейчас посмотрим на примере одного города (чтобы не тратить сразу много запросов, а то лимит 1000), что у нас для него будет, возьмем самый большой город - Москву

In [27]:
for city in found:
  if city == 'Москва':
    print(city, found[city])
    break

Москва 32

https://docs.2gis.com/api/search/places/reference/3.0/items/#tag/Katalog/paths/~13.0~1items/get

In [28]:
moscow_response = requests.get(
    'https://catalog.api.2gis.com/3.0/items',
    params={
        'key': api_key,
        'rubric_id': '164',
        'region_id': '32',
        'page_size': 10, # больше нельзя за 1 запрос, к сожалению (причем в документации написано, что можно 50, но у меня выдавало ошибку при числах больше 10)
        'fields': 'items.point,items.reviews',
        'sort': 'rating' # возьмем самые популярные места
    }
)

moscow_data = moscow_response.json()
print(moscow_data)
moscow_items = moscow_data['result']['items']

print(len(moscow_items), moscow_data['result']['total'])
logging.info('посмотрели на примере Москвы, как будем обращаться ко всем городам')

{'meta': {'api_version': '3.0.20097', 'code': 200, 'issue_date': '20260408'}, 'result': {'items': [{'address_comment': '2 этаж', 'address_name': 'Большая Садовая улица, 5 к1', 'id': '70000001097484511', 'name': 'Infinitum, лаундж-бар', 'point': {'lat': 55.768619, 'lon': 37.592217}, 'reviews': {'general_rating': 5, 'general_review_count': 312, 'general_review_count_with_stars': 314, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 512, 'org_review_count_with_stars': 515}, 'type': 'branch'}, {'address_name': 'улица Солянка, 1/2 ст2', 'id': '70000001105182528', 'name': 'Виновные, винный бар', 'point': {'lat': 55.753816, 'lon': 37.638522}, 'reviews': {'general_rating': 5, 'general_review_count': 173, 'general_review_count_with_stars': 176, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 173, 'org_review_count_with_stars': 176}, 'type': 'branch'}, {'address_name': 'Новоданиловский проезд, 4', 'id': '70000001059377312', 'name': 'Мята Lounge Мануфактура, лаундж-бар', 'point': {'lat': 55.701364, 'lon': 37.624736}, 'reviews': {'general_rating': 5, 'general_review_count': 692, 'general_review_count_with_stars': 711, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 4.8, 'org_review_count': 18444, 'org_review_count_with_stars': 24383}, 'type': 'branch'}, {'address_comment': '1 этаж', 'address_name': 'улица Чехова, 16', 'id': '70000001060297794', 'name': 'gino, ресторан', 'point': {'lat': 55.145512, 'lon': 37.477682}, 'reviews': {'general_rating': 5, 'general_review_count': 73, 'general_review_count_with_stars': 817, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 73, 'org_review_count_with_stars': 817}, 'type': 'branch'}, {'address_comment': '3 этаж', 'address_name': 'Новоясеневский проспект, 1', 'id': '70000001095769133', 'name': 'Барвиха lounge, лаундж-бар', 'point': {'lat': 55.61957, 'lon': 37.508721}, 'reviews': {'general_rating': 5, 'general_review_count': 216, 'general_review_count_with_stars': 222, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 7283, 'org_review_count_with_stars': 8195}, 'type': 'branch'}, {'address_comment': '2 этаж', 'address_name': 'Можайское шоссе, 34а', 'id': '70000001096877157', 'name': 'Hedo, ресторан', 'point': {'lat': 55.719496, 'lon': 37.417212}, 'reviews': {'general_rating': 5, 'general_review_count': 168, 'general_review_count_with_stars': 1156, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 168, 'org_review_count_with_stars': 1156}, 'type': 'branch'}, {'address_comment': '1-2 этаж', 'address_name': 'улица Ленина, 23', 'full_name': 'Дзержинский, улица Ленина, 23', 'id': '70000001035229840', 'name': 'Сказка Лаундж, ресторан', 'point': {'lat': 55.632467, 'lon': 37.847842}, 'purpose_name': 'Ресторан', 'reviews': {'general_rating': 5, 'general_review_count': 246, 'general_review_count_with_stars': 250, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 246, 'org_review_count_with_stars': 250}, 'type': 'branch'}, {'address_comment': '1 этаж', 'address_name': 'Новорязанская улица, 23 ст3', 'id': '70000001101977508', 'name': 'Vasilchuki Chaihona №1, ресторан', 'point': {'lat': 55.773269, 'lon': 37.662534}, 'reviews': {'general_rating': 5, 'general_review_count': 200, 'general_review_count_with_stars': 1780, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 4.9, 'org_review_count': 9576, 'org_review_count_with_stars': 161593}, 'type': 'branch'}, {'address_comment': '1 этаж', 'address_name': 'бульвар Братьев Весниных, 2', 'id': '70000001100566075', 'name': 'Сыроварня, ресторан', 'point': {'lat': 55.699111, 'lon': 37.639133}, 'reviews': {'general_rating': 5, 'general_review_count': 315, 'general_review_count_with_stars': 1712, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 5, 'org_review_count': 315, 'org_review_count_with_stars': 1712}, 'type': 'branch'}, {'address_comment': '1 этаж', 'address_name': 'деревня Лапшинка, вл8 к12', 'id': '70000001090198654', 'name': 'Сыроварня, ресторан', 'point': {'lat': 55.611086, 'lon': 37.335351}, 'reviews': {'general_rating': 5, 'general_review_count': 1388, 'general_review_count_with_stars': 1427, 'is_reviewable': True, 'is_reviewable_on_flamp': True, 'items': [{'is_reviewable': True, 'tag': '2gis_reviews'}, {'is_reviewable': True, 'tag': 'flamp'}], 'org_rating': 4.9, 'org_review_count': 20672, 'org_review_count_with_stars': 207679}, 'type': 'branch'}], 'total': 3950}}
10 3950

Пробуем для всех наших городов найти места

Тут сразу уточню, что этот код я переделывал несколько раз. Код в том виде, который написан тут, по идее, должен работать, но в первый раз была ошибка, что general_rating был не везде

На втором запуске спустя ~355 запросов у какого-то элемента стало отсутствовать поле result, поэтому был добавлен блок, который учитывает такие проблемы + стало интересно посмотреть, где ошибка

In [ ]:
all_places = []

for city, city_id in found.items():
  for rubric, rubric_id in rubrics.items():
    response = requests.get(
        'https://catalog.api.2gis.com/3.0/items',
        params={
            'key': api_key,
            'rubric_id': rubric_id,
            'region_id': city_id,
            'page_size': 10,
            'fields': 'items.point,items.reviews',
            'sort': 'rating'
        }
    )
    data = response.json()
    if 'result' not in data: # пришлось пожертвовать 35% лимита запросов, чтобы понять, что этот блок нужен
              print(f'Ошибка: {city} / {rubric}: {data}')
              continue
    ditems = data['result']['items']

    for place in ditems:
      if 'name' in place:
        name = place['name']
      else:
        name = ''

      if 'point' in place:
        lat = place['point']['lat'] if 'lat' in place['point'] else None
        lon = place['point']['lon'] if 'lon' in place['point'] else None
      else:
        lat = None
        lon = None

      if 'reviews' in place:
        rating = place['reviews']['general_rating'] if 'general_rating' in place['reviews'] else None
        review_count = place['reviews']['general_review_count'] if 'general_review_count' in place['reviews'] else 0
      else:
        rating = None
        review_count = 0

      all_places.append({
          'city': city,
          'rubric': rubric,
          'name': name,
          'lat': lat,
          'lon': lon,
          'rating': rating,
          'review_count': review_count
      })
    time.sleep(0.5)

  pd.DataFrame(all_places).to_csv('places_2gis.csv', index=False, encoding='utf-8-sig')

Ошибка: Хасавюрт / Интересные здания: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260407'}}

In [29]:
logging.info('попробовали сделать перебор всех интересных мест по всем городам, но возникла ошибка')

Как будет видно до следующего запуска похожего кода, здесь получилось что-то не то. Я немного напутал с отступами и у меня перебиралась только одна категория

In [ ]:
print(all_places)

[{'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Тубтен Шедруб Линг, буддийский монастырь', 'lat': 51.691496, 'lon': 94.404949, 'rating': 5, 'review_count': 33}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Краеведческий музей им. Н.М. Мартьянова', 'lat': 53.709695, 'lon': 91.688606, 'rating': 4.9, 'review_count': 80}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Хурээ Цеченлинг, буддийский храм', 'lat': 51.723753, 'lon': 94.450489, 'rating': 5, 'review_count': 15}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Октябрьская улица, 65', 'lat': 53.709955, 'lon': 91.69699, 'rating': 5, 'review_count': 14}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Драматический театр', 'lat': 53.709711, 'lon': 91.683435, 'rating': 4.9, 'review_count': 43}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Саяно-Шушенская ГЭС им. П.С. Непорожнего', 'lat': 52.829654, 'lon': 91.368377, 'rating': 4.9, 'review_count': 64}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Собор Николая Чудотворца', 'lat': 53.710005, 'lon': 91.479213, 'rating': 5, 'review_count': 10}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Национальный центр народного творчества им. С.П. Кадышева', 'lat': 53.724394, 'lon': 91.448497, 'rating': 4.8, 'review_count': 23}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Краеведческий музей им. Л.Р. Кызласова', 'lat': 53.720434, 'lon': 91.473981, 'rating': 4.8, 'review_count': 203}, {'city': 'Абакан', 'rubric': 'Интересные здания', 'name': 'Тувгосфилармония им. В.М. Халилова', 'lat': 51.722006, 'lon': 94.433917, 'rating': 5, 'review_count': 4}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Свято-Троицкий кафедральный собор во имя святой живоначальной троицы', 'lat': 64.735578, 'lon': 177.521834, 'rating': 4.8, 'review_count': 6}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Полярный, кинотеатр', 'lat': 64.734317, 'lon': 177.51767, 'rating': 4.3, 'review_count': 13}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Дом народного творчества городского округа Анадырь', 'lat': 64.736455, 'lon': 177.520533, 'rating': 4.5, 'review_count': 4}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Ледовый дворец', 'lat': 64.733283, 'lon': 177.50594, 'rating': None, 'review_count': 0}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Кафе', 'lat': 64.737219, 'lon': 177.512113, 'rating': 5, 'review_count': 3}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Православный храм в честь князя Владимира', 'lat': 64.730822, 'lon': 177.692211, 'rating': None, 'review_count': 0}, {'city': 'Анадырь', 'rubric': 'Интересные здания', 'name': 'Религиозное сооружение', 'lat': 64.740176, 'lon': 177.688251, 'rating': None, 'review_count': 0}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Драматический театр', 'lat': 64.551287, 'lon': 39.793611, 'rating': 4.9, 'review_count': 55}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Михаило-Архангельский кафедральный собор', 'lat': 64.529293, 'lon': 40.536251, 'rating': 5, 'review_count': 18}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Архангельские гостиные дворы, краеведческий музей', 'lat': 64.538211, 'lon': 40.509813, 'rating': 4.8, 'review_count': 74}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Архангельский водорослевый комбинат', 'lat': 64.49938, 'lon': 40.686481, 'rating': 4.9, 'review_count': 62}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Поморская филармония', 'lat': 64.545457, 'lon': 40.514961, 'rating': 4.8, 'review_count': 50}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Северный государственный медицинский университет', 'lat': 64.542137, 'lon': 40.514001, 'rating': 4.7, 'review_count': 16}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Театр драмы им. М.В. Ломоносова', 'lat': 64.536359, 'lon': 40.515163, 'rating': 4.7, 'review_count': 124}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Троицкий Пассаж', 'lat': 64.536493, 'lon': 40.519499, 'rating': 5, 'review_count': 4}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Музей художественного освоения Арктики им. А.А. Борисова, музейное объединение', 'lat': 64.533921, 'lon': 40.522813, 'rating': 4.7, 'review_count': 42}, {'city': 'Архангельск', 'rubric': 'Интересные здания', 'name': 'Храм Сретения Господня', 'lat': 64.475638, 'lon': 40.506878, 'rating': 5, 'review_count': 9}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Галактика, студия детских праздников', 'lat': 46.350873, 'lon': 48.02708, 'rating': 5, 'review_count': 122}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Махалля красной мечети №298', 'lat': 46.34522, 'lon': 48.055689, 'rating': 5, 'review_count': 17}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Артиллерийская башня (пыточная), музей', 'lat': 46.351237, 'lon': 48.033844, 'rating': 4.9, 'review_count': 49}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Покровский кафедральный собор', 'lat': 46.363642, 'lon': 48.046384, 'rating': 5, 'review_count': 13}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Драматический театр', 'lat': 46.34828, 'lon': 48.044199, 'rating': 4.9, 'review_count': 143}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Астраханская государственная филармония', 'lat': 46.350781, 'lon': 48.041091, 'rating': 4.9, 'review_count': 71}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Мечеть №1', 'lat': 46.343455, 'lon': 48.03439, 'rating': 5, 'review_count': 12}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Театр кукол', 'lat': 46.353171, 'lon': 48.030877, 'rating': 4.8, 'review_count': 76}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Арбат, торгово-деловой центр', 'lat': 46.351459, 'lon': 48.036613, 'rating': 4.8, 'review_count': 13}, {'city': 'Астрахань', 'rubric': 'Интересные здания', 'name': 'Астраханская, гостиничный комплекс', 'lat': 46.353801, 'lon': 48.032777, 'rating': 4.8, 'review_count': 357}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Храм Святого Димитрия Ростовского', 'lat': 53.329375, 'lon': 83.785742, 'rating': 4.9, 'review_count': 27}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Мемориальный музей Г.С. Титова', 'lat': 53.215675, 'lon': 84.636558, 'rating': 4.9, 'review_count': 72}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Дом под шпилем', 'lat': 53.354018, 'lon': 83.77117, 'rating': 4.9, 'review_count': 86}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Государственная филармония Алтайского края', 'lat': 53.329176, 'lon': 83.788757, 'rating': 4.8, 'review_count': 150}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Красный, универмаг', 'lat': 53.33446, 'lon': 83.792176, 'rating': 4.8, 'review_count': 33}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Театр драмы им. В.М. Шукшина', 'lat': 53.346703, 'lon': 83.77341, 'rating': 4.8, 'review_count': 594}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Русский чай, ресторан', 'lat': 53.330286, 'lon': 83.783982, 'rating': 4.8, 'review_count': 372}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Молодежный театр им. В.С. Золотухина', 'lat': 53.355377, 'lon': 83.770921, 'rating': 4.8, 'review_count': 316}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Никольский храм', 'lat': 53.341542, 'lon': 83.784735, 'rating': 4.8, 'review_count': 54}, {'city': 'Барнаул', 'rubric': 'Интересные здания', 'name': 'Центр детского творчества Центрального района г. Барнаула', 'lat': 53.333242, 'lon': 83.760984, 'rating': 4.9, 'review_count': 13}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Храм святых мучениц Веры, Надежды, Любови и матери их Софии', 'lat': 50.57292, 'lon': 36.571358, 'rating': 5, 'review_count': 13}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Белгородская государственная филармония', 'lat': 50.598699, 'lon': 36.604305, 'rating': 4.7, 'review_count': 64}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Белгородский государственный национальный исследовательский университет, институт инженерных и цифровых технологий', 'lat': 50.593384, 'lon': 36.575902, 'rating': 4.6, 'review_count': 12}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Белгородский государственный литературный музей', 'lat': 50.597589, 'lon': 36.598948, 'rating': 4.8, 'review_count': 12}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Драматический театр им. М.С. Щепкина', 'lat': 50.594349, 'lon': 36.586937, 'rating': 4.5, 'review_count': 71}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Лицей №9', 'lat': 50.601037, 'lon': 36.592173, 'rating': 5, 'review_count': 5}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Храм Святого Великомученика Георгия Победоносца', 'lat': 50.572771, 'lon': 36.570645, 'rating': 5, 'review_count': 5}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Гражданский, бизнес-центр', 'lat': 50.59358, 'lon': 36.598933, 'rating': 4.7, 'review_count': 2}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Белгородский государственный национальный исследовательский университет, институт общественных наук и массовых коммуникаций', 'lat': 50.599026, 'lon': 36.588653, 'rating': 5, 'review_count': 2}, {'city': 'Белгород', 'rubric': 'Интересные здания', 'name': 'Духовно-Просветительский Центр во имя Святителя Иоасафа Белгородского', 'lat': 50.603319, 'lon': 36.600064, 'rating': 5, 'review_count': 3}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Триумфальная арка', 'lat': 50.256763, 'lon': 127.52156, 'rating': 4.9, 'review_count': 129}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Благовещенский государственный педагогический университет, факультет иностранных языков', 'lat': 50.256551, 'lon': 127.541394, 'rating': 4.9, 'review_count': 8}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Амурский областной краеведческий музей им. Г.С. Новикова-Даурского', 'lat': 50.259031, 'lon': 127.524884, 'rating': 4.9, 'review_count': 230}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Центр эстетического воспитания детей им. В.В. Белоглазова', 'lat': 50.257494, 'lon': 127.523389, 'rating': 4.9, 'review_count': 47}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Дальневосточный государственный аграрный университет, факультет агрономии и экологии', 'lat': 50.265559, 'lon': 127.555109, 'rating': 4.9, 'review_count': 4}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Албазинский острог, музейно-культурный центр', 'lat': 50.533666, 'lon': 127.607633, 'rating': 4.8, 'review_count': 103}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Театр драмы', 'lat': 50.259309, 'lon': 127.514092, 'rating': 4.8, 'review_count': 245}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Инь-Ян, медицинский центр', 'lat': 50.264593, 'lon': 127.539, 'rating': 4.7, 'review_count': 159}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Амурский педагогический колледж, отделение №4', 'lat': 50.269001, 'lon': 127.535302, 'rating': 4.8, 'review_count': 10}, {'city': 'Благовещенск', 'rubric': 'Интересные здания', 'name': 'Благовещенский политехнический колледж', 'lat': 50.254595, 'lon': 127.553576, 'rating': 4.8, 'review_count': 9}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Православная церковь Успения Божией матери', 'lat': 56.294276, 'lon': 101.694212, 'rating': 5, 'review_count': 11}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Драматический театр', 'lat': 56.156824, 'lon': 101.623239, 'rating': 4.8, 'review_count': 114}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Алмаз, торговый центр', 'lat': 56.171843, 'lon': 101.618692, 'rating': 4.7, 'review_count': 12}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Комсомольская улица, 77', 'lat': 56.166864, 'lon': 101.618974, 'rating': 5, 'review_count': 18}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Падунские Пороги, железнодорожный вокзал', 'lat': 56.308547, 'lon': 101.72451, 'rating': 4.6, 'review_count': 101}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Храм Всех Святых в земле Российской просиявших', 'lat': 56.182908, 'lon': 101.629306, 'rating': 4.8, 'review_count': 11}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Братский государственный университет', 'lat': 56.30904, 'lon': 101.757412, 'rating': 4.7, 'review_count': 21}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Дворец искусств, г. Братск', 'lat': 56.302323, 'lon': 101.754969, 'rating': 4.6, 'review_count': 34}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Братск-арт', 'lat': 56.14844, 'lon': 101.632611, 'rating': 4.5, 'review_count': 58}, {'city': 'Братск', 'rubric': 'Интересные здания', 'name': 'Братский государственный университет, факультет энергетики и автоматики', 'lat': 56.309449, 'lon': 101.760834, 'rating': 4.6, 'review_count': 5}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Брянский государственный инженерно-технологический университет', 'lat': 53.243394, 'lon': 34.364685, 'rating': 5, 'review_count': 2}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'БУМ сити, торгово-развлекательный центр', 'lat': 53.308119, 'lon': 34.302292, 'rating': 4.8, 'review_count': 148}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Галерея, торгово-офисный центр', 'lat': 53.244162, 'lon': 34.361385, 'rating': 4.9, 'review_count': 7}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Театр драмы им. А.К. Толстого', 'lat': 53.242525, 'lon': 34.361974, 'rating': 4.9, 'review_count': 23}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Брянский государственный технический университет, Корпус №3', 'lat': 53.304704, 'lon': 34.306446, 'rating': 4.9, 'review_count': 7}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Партизанская поляна, мемориальный комплекс', 'lat': 53.235086, 'lon': 34.597525, 'rating': 4.8, 'review_count': 19}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Брянский государственный цирк', 'lat': 53.251691, 'lon': 34.371701, 'rating': 4.5, 'review_count': 35}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Музей братьев Ткачёвых', 'lat': 53.306144, 'lon': 34.314123, 'rating': 5, 'review_count': 6}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Краеведческий музей', 'lat': 53.234001, 'lon': 34.352859, 'rating': 4.6, 'review_count': 25}, {'city': 'Брянск', 'rubric': 'Интересные здания', 'name': 'Церковь Иконы Божией Матери Тихвинская', 'lat': 53.257882, 'lon': 34.378725, 'rating': 5, 'review_count': 4}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Маяк Токаревского', 'lat': 43.073098, 'lon': 131.84308, 'rating': 4.9, 'review_count': 508}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Театр кукол', 'lat': 43.113838, 'lon': 131.892849, 'rating': 4.9, 'review_count': 127}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Дом путешественника Арсеньева', 'lat': 43.112033, 'lon': 131.874822, 'rating': 4.9, 'review_count': 87}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Дальневосточный юридический институт, филиал университета прокуратуры Российской Федерации', 'lat': 43.117326, 'lon': 131.892503, 'rating': 5, 'review_count': 26}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Военно-исторический музей', 'lat': 43.114438, 'lon': 131.900821, 'rating': 4.9, 'review_count': 170}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Евангелическо-лютеранская церковь Святого Павла', 'lat': 43.115631, 'lon': 131.901912, 'rating': 4.9, 'review_count': 168}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Дом-музей семьи Сухановых', 'lat': 43.117277, 'lon': 131.894983, 'rating': 4.8, 'review_count': 74}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Дальневосточный государственный технический рыбохозяйственный университет, институт заочного обучения', 'lat': 43.116058, 'lon': 131.885304, 'rating': 4.8, 'review_count': 19}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Морской вокзал, многофункциональный комплекс', 'lat': 43.111008, 'lon': 131.882724, 'rating': 4.8, 'review_count': 187}, {'city': 'Владивосток', 'rubric': 'Интересные здания', 'name': 'Драматический театр им. М. Горького', 'lat': 43.115776, 'lon': 131.893326, 'rating': 4.8, 'review_count': 391}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Суннитская Мечеть Мухтарова, Мечеть', 'lat': 43.026101, 'lon': 44.675853, 'rating': 5, 'review_count': 55}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Александровский, гранд-отель', 'lat': 43.030789, 'lon': 44.680113, 'rating': 4.9, 'review_count': 154}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Церковь Рождества Пресвятой Богородицы, г. Владикавказ', 'lat': 43.020007, 'lon': 44.685858, 'rating': 5, 'review_count': 10}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Аланский Свято-Успенский мужской монастырь', 'lat': 42.821824, 'lon': 44.274852, 'rating': 4.9, 'review_count': 30}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Мариинский театр, театр оперы и балета', 'lat': 43.031117, 'lon': 44.676418, 'rating': 4.9, 'review_count': 12}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Собор Святого Георгия Победоносца', 'lat': 43.030189, 'lon': 44.662189, 'rating': 5, 'review_count': 9}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Армянская апостольская церковь Святого Григория Просветителя', 'lat': 43.022426, 'lon': 44.681459, 'rating': 5, 'review_count': 5}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Театр им. Е. Вахтангова', 'lat': 43.030332, 'lon': 44.679435, 'rating': 4.9, 'review_count': 9}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Горский государственный аграрный университет', 'lat': 43.035466, 'lon': 44.680393, 'rating': 5, 'review_count': 2}, {'city': 'Владикавказ', 'rubric': 'Интересные здания', 'name': 'Мариинский театр, концертный зал', 'lat': 43.036769, 'lon': 44.677794, 'rating': 4.7, 'review_count': 10}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Старый Сталинград, гостиница', 'lat': 48.708799, 'lon': 44.518053, 'rating': 5, 'review_count': 567}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Сталинградская битва, музей-панорама', 'lat': 48.715061, 'lon': 44.533337, 'rating': 4.9, 'review_count': 752}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Дом Павлова', 'lat': 48.716058, 'lon': 44.53147, 'rating': 5, 'review_count': 29}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Память, музей', 'lat': 48.708748, 'lon': 44.516708, 'rating': 4.9, 'review_count': 60}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Волгоград, отель', 'lat': 48.708008, 'lon': 44.514152, 'rating': 4.8, 'review_count': 676}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Лофт1890, бизнес-центр', 'lat': 48.707272, 'lon': 44.509174, 'rating': 5, 'review_count': 14}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Музей обороны, мемориально-исторический музей', 'lat': 48.711351, 'lon': 44.514706, 'rating': 4.8, 'review_count': 40}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Волгоград Арена, стадион', 'lat': 48.734424, 'lon': 44.549721, 'rating': 4.8, 'review_count': 141}, {'city': 'Волгоград', 'rubric': 'Интересные здания', 'name': 'Интурист, гостиница', 'lat': 48.7089

In [ ]:
df_2gis = pd.DataFrame(all_places)
df_2gis.to_csv('df_2gis', index=False, encoding='utf-8-sig')

In [ ]:
df_2gis.head(20)

,city,rubric,name,lat,lon,rating,review_count
0,Абакан,Интересные здания,"Тубтен Шедруб Линг, буддийский монастырь",51.691496,94.404949,5.0,33
1,Абакан,Интересные здания,Краеведческий музей им. Н.М. Мартьянова,53.709695,91.688606,4.9,80
2,Абакан,Интересные здания,"Хурээ Цеченлинг, буддийский храм",51.723753,94.450489,5.0,15
3,Абакан,Интересные здания,"Октябрьская улица, 65",53.709955,91.696990,5.0,14
4,Абакан,Интересные здания,Драматический театр,53.709711,91.683435,4.9,43
5,Абакан,Интересные здания,Саяно-Шушенская ГЭС им. П.С. Непорожнего,52.829654,91.368377,4.9,64
6,Абакан,Интересные здания,Собор Николая Чудотворца,53.710005,91.479213,5.0,10
7,Абакан,Интересные здания,Национальный центр народного творчества им. С....,53.724394,91.448497,4.8,23
8,Абакан,Интересные здания,Краеведческий музей им. Л.Р. Кызласова,53.720434,91.473981,4.8,203
9,Абакан,Интересные здания,Тувгосфилармония им. В.М. Халилова,51.722006,94.433917,5.0,4
10,Анадырь,Интересные здания,Свято-Троицкий кафедральный собор во имя свято...,64.735578,177.521834,4.8,6
11,Анадырь,Интересные здания,"Полярный, кинотеатр",64.734317,177.517670,4.3,13
12,Анадырь,Интересные здания,Дом народного творчества городского округа Ана...,64.736455,177.520533,4.5,4
13,Анадырь,Интересные здания,Ледовый дворец,64.733283,177.505940,NaN,0
14,Анадырь,Интересные здания,Кафе,64.737219,177.512113,5.0,3
15,Анадырь,Интересные здания,Православный храм в честь князя Владимира,64.730822,177.692211,NaN,0
16,Анадырь,Интересные здания,Религиозное сооружение,64.740176,177.688251,NaN,0
17,Архангельск,Интересные здания,Драматический театр,64.551287,39.793611,4.9,55
18,Архангельск,Интересные здания,Михаило-Архангельский кафедральный собор,64.529293,40.536251,5.0,18
19,Архангельск,Интересные здания,"Архангельские гостиные дворы, краеведческий музей",64.538211,40.509813,4.8,74

In [ ]:
print(len(all_places))

798

In [ ]:
print(df_2gis['rubric'].value_counts())

rubric
Интересные здания    798
Name: count, dtype: int64

In [30]:
logging.info('разобрались, в чем ошибка (в отступах), поменяли ключ и начинаем уже реально брать данные о всех интересных местах по всем городам')

Из-за такой ситуации израсходовалось 780/1000 запросов

Поэтому пробуем новый ключ

In [31]:
api_key_new = 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'

In [32]:
logging.info('начинаем сбор, для начала возьмем первую страницу')
all_places = []

for city, city_id in found.items():
  for rubric, rubric_id in rubrics.items():
    response = requests.get(
        'https://catalog.api.2gis.com/3.0/items',
        params={
            'key': api_key_new,
            'rubric_id': rubric_id,
            'region_id': city_id,
            'page': 1,
            'page_size': 10,
            'fields': 'items.point,items.reviews',
            'sort': 'rating'
        }
    )
    data = response.json()
    if 'result' not in data:
      logging.warning(f'Ошибка: {city} / {rubric}: {data}')
      print(f'Ошибка: {city} / {rubric}: {data}')
      continue
    ditems = data['result']['items']

    for place in ditems:
      if 'name' in place:
        name = place['name']
      else:
        name = ''

      if 'point' in place:
        lat = place['point']['lat'] if 'lat' in place['point'] else None
        lon = place['point']['lon'] if 'lon' in place['point'] else None
      else:
        lat = None
        lon = None

      if 'reviews' in place:
        rating = place['reviews']['general_rating'] if 'general_rating' in place['reviews'] else None
        review_count = place['reviews']['general_review_count'] if 'general_review_count' in place['reviews'] else 0
      else:
        rating = None
        review_count = 0

      all_places.append({
          'city': city,
          'rubric': rubric,
          'name': name,
          'lat': lat,
          'lon': lon,
          'rating': rating,
          'review_count': review_count
      })
    time.sleep(0.5)

  pd.DataFrame(all_places).to_csv('places_2gis_1.csv', index=False, encoding='utf-8-sig')

Ошибка: Анадырь / Театры: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Грозный / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Орск / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Рыбинск / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Сыктывкар / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Хасавюрт / Театры: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Хасавюрт / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Хасавюрт / Интересные здания: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Шахты / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}
Ошибка: Элиста / Природные достопримечательности: {'meta': {'api_version': '3.0.20097', 'code': 404, 'error': {'message': 'Results not found', 'type': 'itemNotFound'}, 'issue_date': '20260408'}}

In [33]:
logging.info(f'сбор данных по первым страницам завершен, собрали и сохранили {len(all_places)} мест')

In [34]:
pd.DataFrame(all_places)['rubric'].value_counts()

rubric
Рестораны                          810
Интересные здания                  798
Музеи                              757
Природные достопримечательности    563
Театры                             548
Name: count, dtype: int64

В данных все норм, код пофиксили

Ошибки дальше выводить не буду, нет смысла, но оставлю в логах

Так как у нас свежий апи ключ, сделаем сразу вторую страницу, чтобы было больше данных

In [35]:
logging.info('начинаем сбор вторых страниц')
all_places2 = []

for city, city_id in found.items():
  for rubric, rubric_id in rubrics.items():
    response = requests.get(
        'https://catalog.api.2gis.com/3.0/items',
        params={
            'key': api_key_new,
            'rubric_id': rubric_id,
            'region_id': city_id,
            'page': 2,
            'page_size': 10,
            'fields': 'items.point,items.reviews',
            'sort': 'rating'
        }
    )
    data = response.json()
    if 'result' not in data:
      logging.warning(f'Ошибка: {city} / {rubric}: {data}')
      continue
    ditems = data['result']['items']

    for place in ditems:
      if 'name' in place:
        name = place['name']
      else:
        name = ''

      if 'point' in place:
        lat = place['point']['lat'] if 'lat' in place['point'] else None
        lon = place['point']['lon'] if 'lon' in place['point'] else None
      else:
        lat = None
        lon = None

      if 'reviews' in place:
        rating = place['reviews']['general_rating'] if 'general_rating' in place['reviews'] else None
        review_count = place['reviews']['general_review_count'] if 'general_review_count' in place['reviews'] else 0
      else:
        rating = None
        review_count = 0

      all_places2.append({
          'city': city,
          'rubric': rubric,
          'name': name,
          'lat': lat,
          'lon': lon,
          'rating': rating,
          'review_count': review_count
      })
    time.sleep(0.5)

  pd.DataFrame(all_places2).to_csv('places_2gis_2.csv', index=False, encoding='utf-8-sig')

In [36]:
logging.info(f'сбор данных по вторым страницам завершен, собрали и сохранили {len(all_places2)} мест')

In [37]:
pd.DataFrame(all_places2)['rubric'].value_counts()

rubric
Интересные здания                  748
Рестораны                          744
Музеи                              604
Природные достопримечательности    390
Театры                             191
Name: count, dtype: int64

Тут появился еще один апи ключ...

Поэтому сделаем 3 и 4 страницы

In [38]:
the_newest_key = 'zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzz'

In [39]:
logging.info('взяли новый ключ, собираем данные третьих страниц')
all_places3_new = []

for city, city_id in found.items():
  for rubric, rubric_id in rubrics.items():
    response = requests.get(
        'https://catalog.api.2gis.com/3.0/items',
        params={
            'key': the_newest_key,
            'rubric_id': rubric_id,
            'region_id': city_id,
            'page': 3,
            'page_size': 10,
            'fields': 'items.point,items.reviews',
            'sort': 'rating'
        }
    )
    data = response.json()
    if 'result' not in data:
      logging.warning(f'Ошибка: {city} / {rubric}: {data}')
      continue
    ditems = data['result']['items']

    for place in ditems:
      if 'name' in place:
        name = place['name']
      else:
        name = ''

      if 'point' in place:
        lat = place['point']['lat'] if 'lat' in place['point'] else None
        lon = place['point']['lon'] if 'lon' in place['point'] else None
      else:
        lat = None
        lon = None

      if 'reviews' in place:
        rating = place['reviews']['general_rating'] if 'general_rating' in place['reviews'] else None
        review_count = place['reviews']['general_review_count'] if 'general_review_count' in place['reviews'] else 0
      else:
        rating = None
        review_count = 0

      all_places3_new.append({
          'city': city,
          'rubric': rubric,
          'name': name,
          'lat': lat,
          'lon': lon,
          'rating': rating,
          'review_count': review_count
      })
    time.sleep(0.5)

  pd.DataFrame(all_places3_new).to_csv('places_2gis_3_new.csv', index=False, encoding='utf-8-sig') # не 3, а 3_new, потому что сначала забыл ключ другой поставить

In [40]:
logging.info(f'сбор данных по третьим страницам завершен, собрали и сохранили {len(all_places3_new)} мест')

In [41]:
pd.DataFrame(all_places3_new)['rubric'].value_counts()

rubric
Интересные здания                  709
Рестораны                          678
Музеи                              498
Природные достопримечательности    301
Театры                              87
Name: count, dtype: int64

In [42]:
logging.info('наконец, собираем четвертые страницы')
all_places4 = []

for city, city_id in found.items():
  for rubric, rubric_id in rubrics.items():
    response = requests.get(
        'https://catalog.api.2gis.com/3.0/items',
        params={
            'key': the_newest_key,
            'rubric_id': rubric_id,
            'region_id': city_id,
            'page': 4,
            'page_size': 10,
            'fields': 'items.point,items.reviews',
            'sort': 'rating'
        }
    )
    data = response.json()
    if 'result' not in data:
      logging.warning(f'Ошибка: {city} / {rubric}: {data}')
      continue
    ditems = data['result']['items']

    for place in ditems:
      if 'name' in place:
        name = place['name']
      else:
        name = ''

      if 'point' in place:
        lat = place['point']['lat'] if 'lat' in place['point'] else None
        lon = place['point']['lon'] if 'lon' in place['point'] else None
      else:
        lat = None
        lon = None

      if 'reviews' in place:
        rating = place['reviews']['general_rating'] if 'general_rating' in place['reviews'] else None
        review_count = place['reviews']['general_review_count'] if 'general_review_count' in place['reviews'] else 0
      else:
        rating = None
        review_count = 0

      all_places4.append({
          'city': city,
          'rubric': rubric,
          'name': name,
          'lat': lat,
          'lon': lon,
          'rating': rating,
          'review_count': review_count
      })
    time.sleep(0.5)

  pd.DataFrame(all_places4).to_csv('places_2gis_4.csv', index=False, encoding='utf-8-sig')

In [43]:
logging.info(f'сбор данных по четвертым страницам завершен, собрали и сохранили {len(all_places3_new)} мест')

In [44]:
pd.DataFrame(all_places4)['rubric'].value_counts()

rubric
Интересные здания                  651
Рестораны                          631
Музеи                              406
Природные достопримечательности    232
Театры                              37
Name: count, dtype: int64

Все 4 страницы сделаны, теперь соберем все воедино

In [45]:
df1 = pd.read_csv('places_2gis_1.csv', encoding='utf-8-sig')
df2 = pd.read_csv('places_2gis_2.csv', encoding='utf-8-sig')
df3 = pd.read_csv('places_2gis_3_new.csv', encoding='utf-8-sig')
df4 = pd.read_csv('places_2gis_4.csv', encoding='utf-8-sig')

df_all = pd.concat([df1, df2, df3, df4], ignore_index=True)
logging.info(f'собрали все места в единый датасет, в нем {df_all.shape[0]} наблюдений')

Ну и посмотрим немного статистики по получившемуся датафрейму + сохраним его

In [46]:
df_all.shape

(10383, 7)

In [47]:
df_all.head()

,city,rubric,name,lat,lon,rating,review_count
0,Абакан,Рестораны,Лисья нора,52.849878,91.420183,4.9,401
1,Абакан,Рестораны,"STIX, бельгийский ресторан",53.721736,91.444138,4.7,648
2,Абакан,Рестораны,"Мажор, караоке-бар",53.725752,91.456086,4.7,309
3,Абакан,Рестораны,"Мадрид, кафе",53.727392,91.437827,4.6,300
4,Абакан,Рестораны,"Баран и бисер, ресторан",53.724203,91.443411,4.6,647

In [48]:
df_all['rubric'].value_counts()

rubric
Интересные здания                  2906
Рестораны                          2863
Музеи                              2265
Природные достопримечательности    1486
Театры                              863
Name: count, dtype: int64

In [49]:
df_all['city'].value_counts()

city
Екатеринбург       200
Москва             200
Санкт-Петербург    200
Новосибирск        194
Красноярск         193
                  ...
Магадан             35
Элиста              33
Шахты               29
Хасавюрт            15
Анадырь             12
Name: count, Length: 82, dtype: int64

In [50]:
df_all.to_csv('places_2gis_all.csv', index=False, encoding='utf-8-sig')